### ISSUE TITLE
[PE-D] List reflects the wrong index for the last member. Cannot delete the member based on the index that is reflected.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#177] opened 2021-10-30 16:38 UTC
![Screenshot 2021-10-29 at 5.12.54 PM.png](https://raw.githubusercontent.com/nguyin/ped/main/files/4ca6fc57-fcf0-451c-b823-c7f1241bf659.png)
![Screenshot 2021-10-29 at 5.13.24 PM.png](https://raw.githubusercontent.com/nguyin/ped/main/files/c2af9b33-a2e7-4ce7-9b3f-beb72ec001a0.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nguyin/ped#6

**Comment by izdiyadfrhn** [comment] 2021-11-01 01:58
Duplicate of #182

**Closed by izdiyadfrhn** 2021-11-01 01:58 UTC
