### ISSUE TITLE
[PE-D] delete /m function randomly deletes member with the same name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F12-4/tp#158] opened 2021-10-30 15:13 UTC
![Screenshot 2021-10-29 at 4.56.30 PM.png](https://raw.githubusercontent.com/nguyin/ped/main/files/b5669e10-3572-42f7-821b-852c2292f820.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: nguyin/ped#1

**Comment by izdiyadfrhn** [comment] 2021-11-01 01:50
Duplicate of #182

**Closed by izdiyadfrhn** 2021-11-01 01:50 UTC
